---
- hosts: webservers
  remote_user: ubuntu
  tasks:
    - name: Run start server.sh script
      ansible.builtin.command: /home/ubuntu/philosophers-football/server/start.sh
      become: yes
      args:
        chdir: /home/ubuntu/philosophers-football